version: "3"
services:

  authservice:
    build:
      context: ./backend/authservice
      dockerfile: Dockerfile
    environment:
    - DB_DATABASE=esi
    - DB_USERNAME=root
    - DB_PASSWORD=root
    - DB_HOST=db
    - USERS_SERVICE_BASE_URI=userservice:8001
    ports:
    - "8000:80"
    depends_on:
    - db
    - userservice

  userservice:
    build:
      context: ./backend/userservice
      dockerfile: Dockerfile
    environment:
    - DB_DATABASE=esi
    - DB_USERNAME=root
    - DB_PASSWORD=root
    - DB_HOST=db
    ports:
    - "8001:80"
    depends_on:
    - db

  app:
    build:
      context: ./tp
      dockerfile: Dockerfile
    ports:
    - "4200:80"
    depends_on:
    - db
    

  db:
    build:
      context: ./sql_dump
      dockerfile: Dockerfile
    ports:
    - "6603:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=root
    command: ['--default-authentication-plugin=mysql_native_password']
    
