version: "3"
services:

  authservice:
    build:
      context: .
      dockerfile: backend/authservice/Dockerfile
    environment:
    - DB_DATABASE=esi
    - DB_USERNAME=root
    - DB_PASSWORD=root
    - DB_HOST=db
    - DB_PORT=6603
    ports:
    - "8000:80"
    volumes:
    - ./backend/authservice:/var/www
    depends_on:
    - db
    - userservice

  userservice:
    build:
      context: .
      dockerfile: backend/userservice/Dockerfile
    environment:
    - DB_DATABASE=esi
    - DB_USERNAME=root
    - DB_PASSWORD=root
    - DB_HOST=db
    - DB_PORT=6603
    ports:
    - "8001:80"
    volumes:
    - ./backend/userservice:/var/www
    depends_on:
    - db

  app:
    build:
      context: .
      dockerfile: tp/Dockerfile
    ports:
    - "8001:80"
    depends_on:
    - db

  db:
    image: mysql:5.7
    ports:
    - "6603:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_USER=root
    - MYSQL_PASSWORD=root
    - MYSQL_DATABASE=esi
    volumes:
    - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  mysql_data: { driver: local }